kapiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bms-container
        image: 653293365854.dkr.ecr.ap-south-1.amazonaws.com/bookmyshow:latest
        ports:
        - containerPort: 3000

